### ISSUE TITLE
Chinese-Word-Vectors

### ISSUE THREAD

**Issue by ghost** [zake7749/WSDM-2019#2]
hello. SGNS version of Chinese-Word-Vectors not downloaded in my country. I try to download it with other IP. but it isn't available. can you upload it on drive or Dropbox, please?
https://pan.baidu.com/s/1oJol-GaRMk4-8Ejpzxo6Gw

**Comment by zake7749** [comment]
Hello @fariba07,

It concerns me that I have no right to share the whole vector publicly, so I upload a small [cache](https://drive.google.com/file/d/1RBuWTsx6MCbzyoZwQ0-7xlq3moymYX6M/view?usp=sharing) which is only composed of the words I used in this competition.

**Comment by ghost** [comment]
Thank you very much
